### ISSUE TITLE
Can no more build with latest libevhtp 1.2.11n release

### ISSUE THREAD

**Issue by david-geiger** [haiwen/seafile#1631]
Hi,

I try to compile the server part of seafile with latest libevhtp (1.2.11n) but I get some errors due to unfounded header files:

http-server.c:15:19: fatal error: evhtp.h: No such file or directory
compilation terminated.
Makefile:692: recipe for target 'http-server.o' failed
make[3]: **\* [http-server.o] Error 1
make[3]: Leaving directory '/home/david/mgarepo/Patch_fix/seafile/BUILD/seafile-5.1.1/server'
make[3]: **\* Waiting for unfinished jobs....

Indeed this file was moved from '/include/.h' to '/include/evhtp/.h' directory.

So attached a proposed fix:
![capture d ecran10](https://cloud.githubusercontent.com/assets/4344460/15093741/c0c57266-1490-11e6-8882-a3aeaf6cac34.png)

Regards,
David

**Comment by killing** [comment]
As suggested in the build documentation, you should use libevhtp version 1.1.6. That library seems to be constantly changing and sometimes breaks API or behavior.
