### ISSUE TITLE
Seahub fails to start after upgrade to 7.1.4

### ISSUE THREAD

**Issue by angelo-v** [haiwen/seafile#2342]
I followed the [upgrade notes](https://download.seafile.com/published/seafile-manual/upgrade/upgrade_notes_for_7.1.x.md).

As described in the FAQ on that page, I set `daemon = False` and ran started seahub via CLI. I am getting this error there:

```                                             
Starting seahub at port 8000 ...                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/seafile/seafile-server-7.1.4/seahub/seahub/avatar/models.py", line 23, in <module>                                                                                                                   
    from PIL import Image                                                                                                                                                                                          
  File "/home/seafile/seafile-server-7.1.4/seahub/thirdpart/PIL/Image.py", line 93, in <module>                                                                                                                    
    from . import _imaging as core
ImportError: cannot import name '_imaging'
```

I am running on a Raspberry Pi

```
System:    Host: raspberrypi Kernel: 4.19.66-v7+ armv7l (32 bit) Console: tty 0
           Distro: Raspbian GNU/Linux 9 (stretch)```

**Comment by angelo-v** [comment]
It might me worth mentioning, that the installation of `pylibmc` with pip3 was not possible and instead I used `sudo apt install python3-pylibmc`.

**Comment by angelo-v** [comment]
[The forum solved my issue](https://forum.seafile.com/t/seafile-server-7-1-4-for-raspberry-pi-is-ready-23-05-2020/).
