### ISSUE TITLE
seaf-daemon crashes on Ubuntu Artful

### ISSUE THREAD

**Issue by teknoraver** [haiwen/seafile#1955]
seafile applet and daemon doens't start on latest Ubuntu:

```
$ seaf-daemon -c /home/matteo/.ccnet -d /home/matteo/Seafile/.seafile-data -w /home/matteo/Seafile
**
GLib:ERROR:../../../../glib/ghash.c:377:g_hash_table_lookup_node: assertion failed: (hash_table->ref_count > 0)
Aborted
```

```
matteo@turbo:~$ gdb -q seaf-daemon
Reading symbols from seaf-daemon...(no debugging symbols found)...done.
(gdb) run -c /home/matteo/.ccnet -d /home/matteo/Seafile/.seafile-data -w /home/matteo/Seafile
Starting program: /usr/bin/seaf-daemon -c /home/matteo/.ccnet -d /home/matteo/Seafile/.seafile-data -w /home/matteo/Seafile
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff05fc700 (LWP 9267)]
[New Thread 0x7fffefdfb700 (LWP 9268)]
[New Thread 0x7fffef5fa700 (LWP 9269)]
[New Thread 0x7fffeedf9700 (LWP 9270)]
[Thread 0x7fffeedf9700 (LWP 9270) exited]

Thread 1 "seaf-daemon" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x00007ffff6684634 in g_hash_table_lookup () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7214931 in cevent_manager_register () at /usr/lib/x86_64-linux-gnu/libccnet.so.0
#3  0x000055555556cadf in  ()
#4  0x00005555555843bb in  ()
#5  0x000055555558461b in  ()
#6  0x000055555556673b in  ()
#7  0x00007ffff72152a9 in  () at /usr/lib/x86_64-linux-gnu/libccnet.so.0
#8  0x00007ffff6dc86d4 in  () at /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#9  0x00007ffff6dc5420 in event_base_loop () at /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#10 0x00007ffff7214407 in ccnet_main () at /usr/lib/x86_64-linux-gnu/libccnet.so.0
#11 0x000055555555dc19 in  ()
#12 0x00007ffff59eb421 in __libc_start_main (main=0x55555555cdf0, argc=7, argv=0x7fffffffdf08, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdef8) at ../csu/libc-start.c:291
#13 0x000055555555dd7a in  ()
(gdb) 
```

```
$ strace seaf-daemon -c /home/matteo/.ccnet -d /home/matteo/Seafile/.seafile-data -w /home/matteo/Seafile
[...]
access("/media/data/Musica", F_OK)      = 0
open("/usr/lib/x86_64-linux-gnu/charset.alias", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache", O_RDONLY) = 27
fstat(27, {st_mode=S_IFREG|0644, st_size=26258, ...}) = 0
mmap(NULL, 26258, PROT_READ, MAP_SHARED, 27, 0) = 0x7f2266c62000
close(27)                               = 0
futex(0x7f22649fb8a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(2, "**\nGLib:ERROR:../../../../glib/g"..., 115**
GLib:ERROR:../../../../glib/ghash.c:377:g_hash_table_lookup_node: assertion failed: (hash_table->ref_count > 0)
) = 115
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 9331
gettid()                                = 9331
tgkill(9331, 9331, SIGABRT)             = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=9331, si_uid=1000} ---
+++ killed by SIGABRT +++
Aborted
```

**Comment by killing** [comment]
This may be due to some incompatibility of glib. Once we compile natively on Artful in the future, this should not happen.

**Comment by AlbertWeichselbraun** [comment]
I tried to build the packages on my (artful) machine:

`apt-get -b source`  works well for libsearpc, seafile and seafile-gui but fails for `ccnet` with the following error (although libsearpc-dev and libsearpc1 are installed).

```
gcc -DHAVE_CONFIG_H -I. -I../..  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DCCNET_DAEMON -I../../net/common -I../../include -I../../include/ccnet -I../../lib -I../../include -I../../lib -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/searpc -Wall -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fdebug-prefix-map=/usr/local/src/ccnet-6.0.7=. -fstack-protector-strong -Wformat -Werror=format-security -c -o rpc-service.o `test -f '../common/rpc-service.c' || echo './'`../common/rpc-service.c
../common/rpc-service.c:40:10: fatal error: searpc-signature.h: No such file or directory
 #include "searpc-signature.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:811: recipe for target 'rpc-service.o' failed
make[4]: *** [rpc-service.o] Error 1
make[4]: Leaving directory '/usr/local/src/ccnet-6.0.7/net/daemon'
Makefile:385: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/usr/local/src/ccnet-6.0.7/net'
Makefile:489: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/local/src/ccnet-6.0.7'
Makefile:398: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/local/src/ccnet-6.0.7'
```

`searpc-signature.h` is available in seafile's source directory but it is not included in any of the `lib*.deb` or `*-dev.deb` debian packages.

**Comment by renbag** [comment]
The problem is that seafile-daemon and seafile-gui were build with dependency on libevent-2.0-5, while ccnet was build with dependency on libevent-2.1-6. You can download libevent-2.0-5 from zesty and manually install it with dpkg -i, then install seafile-gui from artful. After this, modify the symbolic link /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5 and point it to /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6.0.2.

**Comment by lins05** [comment]
It has been fixed and the PPA has been updated. You can now install seafile client on ubuntu 17.10 by:

```sh
sudo apt-get update -q
sudo apt-get install -y seafile-gui
```
